pan_controller:
    type: effort_controllers/JointVelocityController
    joint: pan_joint
    pid: {p: 32.0, i: 0.0, d: 0.0} #32.0 0.0 0.0

tilt_controller:
    type: effort_controllers/JointVelocityController
    joint: tilt_joint
    pid: {p: 32.0, i: 0.0, d: 0.0}

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    
